---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: policygen-users
  namespace: policy-generator
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - policygen-users
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: policygen-testuser-channel
  namespace: policy-generator
spec:
  type: Git
  pathname: 'https://github.com/giovannisciortino/gitops-examples.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: /acm_app_sub_policygen_example
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: policygen-users
  name: policygen-users-subscription
  namespace: policy-generator
spec:
  allow:
    - apiVersion: policy.open-cluster-management.io/v1
      kinds:
        - "*"
    - apiVersion: cluster.open-cluster-management.io/v1beta1
      kinds:
        - Placement
  channel: policy-generator/policygen-testuser-channel
  placement:
    placementRef:
      kind: Placement
      name: policygen-testusers-placement
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: policygen-users
  name: policygen-testusers-placement
  namespace: policy-generator
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - local-cluster
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists