apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - argocd-openshift-gitops.yaml
  - argocd-appproject/cluster-project.yaml


patchesStrategicMerge:
  - clusterrolebinding.yaml
